// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":return img`
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef............
.ffffee2222ef...........
.fe222ffffe2f...........
fffffffeeefff...........
ffe44ebf44eef...........
fee4d41fddef............
.feee4ddddf.............
..fdde444ef.............
..fdde22ccc.............
...eef22cdc.............
...f4444cddc............
....fffffcddc...........
.....fff..cddc..........
...........cdc..........
............cc..........
........................
........................
........................
........................
........................
........................
`;
            case "image2":return img`
. . . . . . . f f . . . . . . . 
. . . . . f f 4 4 f f . . . . . 
. . . . f 5 4 5 5 4 5 f . . . . 
. . . f e 4 5 5 5 5 4 e f . . . 
. . f b 3 e 4 4 4 4 e 3 b f . . 
. f e 3 3 3 3 3 3 3 3 3 3 e f . 
. f 3 3 e b 3 e e 3 b e 3 3 f . 
. f b 3 f f e e e e f f 3 b f . 
f f b b f b f e e f b f b b f f 
f b b b e 1 f 4 4 f 1 e b b b f 
. f b b e e 4 4 4 4 4 f b b f . 
. . f 4 4 4 e d d d b f e f . . 
. . f e 4 4 e d d d d c 4 e . . 
. . . f e e d d b d b b f e . . 
. . . f f 1 d 1 d 1 1 f f . . . 
. . . . . f f f b b f . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
